options(stringsAsFactors=FALSE,warn=1);set.seed(20260811)
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE);base<-Sys.getenv("CIMMYT_ANALYSIS_ROOT",unset=root)
longfile<-file.path(base,"history","standardized","historical_long_primary_observed.csv")
portfile<-file.path(base,"history","validation_portfolio_analysis","tables","01_nonredundant_validation_portfolio.csv")
out<-file.path(base,"history","environment_adjusted_response_analysis");tabdir<-file.path(out,"tables");figdir<-file.path(out,"figures");repdir<-file.path(out,"reports");logdir<-file.path(out,"logs")
for(p in c(tabdir,figdir,repdir,logdir))dir.create(p,recursive=TRUE,showWarnings=FALSE)
write_out<-function(x,n)write.csv(x,file.path(tabdir,n),row.names=FALSE,na="",fileEncoding="UTF-8")
qf<-function(x,p)unname(quantile(x,p,na.rm=TRUE,type=7));ci<-function(x)c(qf(x,.025),qf(x,.975))
d<-read.csv(longfile,check.names=FALSE,na.strings=c("","NA"),encoding="UTF-8-BOM");p<-read.csv(portfile,check.names=FALSE);input_rows<-nrow(d)
d$GID<-trimws(as.character(d$GID));d<-d[!is.na(d$GID)&d$GID!="",];d$env_id<-paste(d$nursery,d$environment,sep="::")
ids<-as.character(p$GID[p$selected_for_resistance_validation]);stopifnot(input_rows==30475,!any(d$nursery=="15HZAN"),length(ids)==14)
# Environment pressure is estimated without the 14 focal candidates to avoid circularity.
bg<-d[!d$GID%in%ids,];env<-do.call(rbind,lapply(split(seq_len(nrow(bg)),bg$env_id),function(ii){z<-bg[ii,];data.frame(env_id=z$env_id[1],nursery=z$nursery[1],environment=z$environment[1],location=z$location[1],year=z$year[1],sowing=z$sowing[1],background_n=nrow(z),pressure_median=median(z$disease_index_pct),pressure_q75=qf(z$disease_index_pct,.75),pressure_q90=qf(z$disease_index_pct,.9),pressure_iqr=IQR(z$disease_index_pct),zero_fraction=mean(z$disease_index_pct==0))}))
row.names(env)<-NULL;write_out(env,"01_environment_background_pressure.csv")
z<-merge(d[d$GID%in%ids,],env,by=c("env_id","nursery","environment","location","year","sowing"),all.x=TRUE,sort=FALSE)
z$relative_disease<-z$disease_index_pct-z$pressure_median;z$pressure_z<-(z$pressure_median-mean(env$pressure_median))/sd(env$pressure_median)
bg_split<-split(bg$disease_index_pct,bg$env_id);z$background_percentile<-mapply(function(v,e){b<-bg_split[[e]];(sum(b<v)+.5*sum(b==v))/length(b)},z$disease_index_pct,z$env_id);z$relative_rank<-z$background_percentile-.5
ce<-do.call(rbind,lapply(split(seq_len(nrow(z)),interaction(z$GID,z$env_id,drop=TRUE)),function(ii){x<-z[ii,];data.frame(GID=x$GID[1],env_id=x$env_id[1],nursery=x$nursery[1],environment=x$environment[1],location=x$location[1],year=x$year[1],sowing=x$sowing[1],n_obs=nrow(x),pressure_median=x$pressure_median[1],pressure_z=x$pressure_z[1],candidate_median=median(x$disease_index_pct),relative_disease=median(x$relative_disease),relative_rank=median(x$relative_rank),candidate_q90=qf(x$disease_index_pct,.9),failure=median(x$relative_rank)>0|qf(x$disease_index_pct,.9)>30)}));row.names(ce)<-NULL
write_out(ce,"02_candidate_environment_response.csv")
fit_one<-function(x){effect<-median(x$relative_rank);if(length(unique(x$pressure_z))<3)return(c(intercept=effect,slope=NA_real_,r2=NA_real_));m<-lm(relative_rank~pressure_z,x);c(intercept=effect,slope=unname(coef(m)[2]),r2=unname(cor(x$relative_rank,fitted(m))^2))}
B<-1000;res<-list();boots<-list();k<-1
for(id in ids){x<-ce[ce$GID==id,];f<-fit_one(x);bv<-matrix(NA_real_,B,2);for(b in seq_len(B)){e<-sample(unique(x$env_id),length(unique(x$env_id)),replace=TRUE);xb<-do.call(rbind,lapply(e,function(v)x[x$env_id==v,,drop=FALSE]));fb<-fit_one(xb);bv[b,]<-fb[c("intercept","slope")]}
  ic<-ci(bv[,1]);sc<-if(any(is.finite(bv[,2])))ci(bv[,2])else c(NA_real_,NA_real_);res[[k]]<-data.frame(GID=id,n_environments=nrow(x),n_pressure_levels=length(unique(x$pressure_z)),n_years=length(unique(x$year)),adjusted_effect=f["intercept"],adjusted_effect_ci_low=ic[1],adjusted_effect_ci_high=ic[2],pressure_sensitivity=f["slope"],sensitivity_ci_low=sc[1],sensitivity_ci_high=sc[2],reaction_r2=f["r2"],failure_environments=sum(x$failure),failure_fraction=mean(x$failure),max_relative_disease=max(x$relative_disease),worst_environment=x$env_id[which.max(x$relative_disease)][1]);boots[[k]]<-data.frame(GID=id,iteration=seq_len(B),adjusted_effect=bv[,1],pressure_sensitivity=bv[,2]);k<-k+1}
summ<-do.call(rbind,res);summ<-merge(summ,p[,c("GID","portfolio_role")],by="GID",all.x=TRUE);summ$effect_class<-ifelse(summ$adjusted_effect_ci_high<0,"robust_advantage",ifelse(summ$adjusted_effect_ci_low>0,"inferior","uncertain"));summ$sensitivity_class<-ifelse(!is.finite(summ$pressure_sensitivity),"insufficient_pressure_range",ifelse(summ$sensitivity_ci_low>0,"advantage_erodes_under_pressure",ifelse(summ$sensitivity_ci_high<0,"advantage_strengthens_under_pressure","pressure_stable")))
write_out(summ,"03_environment_adjusted_candidate_summary.csv");write_out(do.call(rbind,boots),"04_environment_cluster_bootstrap_draws.csv")
# Year deletion checks whether a single season creates the adjusted advantage.
loo<-do.call(rbind,lapply(ids,function(id){x<-ce[ce$GID==id,];do.call(rbind,lapply(sort(unique(x$year)),function(y){u<-x[x$year!=y,];if(nrow(u)<3)return(NULL);f<-fit_one(u);data.frame(GID=id,omitted_year=y,n_environments=nrow(u),adjusted_effect=f["intercept"],pressure_sensitivity=f["slope"])}))}));write_out(loo,"05_leave_one_year_out_response.csv")
loo_sum<-do.call(rbind,lapply(split(loo,loo$GID),function(x)data.frame(GID=x$GID[1],effect_min=min(x$adjusted_effect),effect_max=max(x$adjusted_effect),slope_min=min(x$pressure_sensitivity),slope_max=max(x$pressure_sensitivity),advantage_preserved=all(x$adjusted_effect<0))));write_out(loo_sum,"06_leave_one_year_out_summary.csv")
# Empirical failure boundary: pressure distribution in passed versus failed candidate-environment events.
boundary<-do.call(rbind,lapply(split(ce,ce$GID),function(x){fail<-x[x$failure,];pass<-x[!x$failure,];data.frame(GID=x$GID[1],n_environment=nrow(x),n_failed=nrow(fail),max_pressure_pass=if(nrow(pass))max(pass$pressure_median)else NA,min_pressure_fail=if(nrow(fail))min(fail$pressure_median)else NA,median_pressure_pass=if(nrow(pass))median(pass$pressure_median)else NA,median_pressure_fail=if(nrow(fail))median(fail$pressure_median)else NA)}));write_out(boundary,"07_empirical_failure_boundaries.csv")
ord<-summ$GID[order(summ$adjusted_effect)];draw_effect<-function(){par(mar=c(4,5,2.2,1),family="sans",cex=.75);s<-summ[match(ord,summ$GID),];y<-seq_len(nrow(s));plot(s$adjusted_effect,y,xlim=range(c(s$adjusted_effect_ci_low,s$adjusted_effect_ci_high,0),na.rm=TRUE),ylim=c(.5,nrow(s)+.5),pch=21,bg=ifelse(s$effect_class=="robust_advantage","#3F6B3A","white"),yaxt="n",xlab="Background-relative rank (0 = environment median)",ylab="");segments(s$adjusted_effect_ci_low,y,s$adjusted_effect_ci_high,y,col="#6B6258");axis(2,at=y,labels=s$GID,las=1,cex.axis=.7);abline(v=0,lty=3,col="#7C817A");title("a  Candidate effects after environmental adjustment",adj=0,font.main=2,cex.main=.95)}
draw_reaction<-function(){par(mar=c(4,4,2.2,1),family="sans",cex=.75);plot(ce$pressure_median,ce$relative_rank,pch=16,col=adjustcolor("#8A8175",.25),xlab="Background environment pressure",ylab="Background-relative candidate rank");abline(h=0,lty=3,col="#7C817A");for(id in ids){x<-ce[ce$GID==id,];if(length(unique(x$pressure_median))>=3){f<-lm(relative_rank~pressure_median,x);xx<-range(x$pressure_median);lines(xx,predict(f,newdata=data.frame(pressure_median=xx)),col=ifelse(summ$effect_class[match(id,summ$GID)]=="robust_advantage","#3F6B3A","#4F718C"),lwd=.8)}};title("b  Observed reaction norms",adj=0,font.main=2,cex.main=.95)}
draw_boundary<-function(){par(mar=c(4,5,2.2,1),family="sans",cex=.75);s<-summ[match(ord,summ$GID),];y<-seq_len(nrow(s));plot(s$failure_fraction,y,xlim=c(0,1),ylim=c(.5,nrow(s)+.5),pch=21,bg="#8B5E3C",yaxt="n",xlab="Fraction of candidate-environment failures",ylab="");axis(2,at=y,labels=s$GID,las=1,cex.axis=.7);title("c  Empirical failure frequency",adj=0,font.main=2,cex.main=.95)}
export_plot<-function(fun,stem,width=183,height=125){w<-width/25.4;h<-height/25.4;if(requireNamespace("svglite",quietly=TRUE))svglite::svglite(file.path(figdir,paste0(stem,".svg")),width=w,height=h,system_fonts=list(sans="Arial"))else svg(file.path(figdir,paste0(stem,".svg")),width=w,height=h,family="sans");fun();dev.off();cairo_pdf(file.path(figdir,paste0(stem,".pdf")),width=w,height=h,family="sans");fun();dev.off();if(requireNamespace("ragg",quietly=TRUE))ragg::agg_tiff(file.path(figdir,paste0(stem,".tiff")),width=w,height=h,units="in",res=600,compression="lzw")else tiff(file.path(figdir,paste0(stem,".tiff")),width=w,height=h,units="in",res=600,compression="lzw",family="sans");fun();dev.off();png(file.path(figdir,paste0(stem,".png")),width=w,height=h,units="in",res=300,family="sans");fun();dev.off()}
export_plot(draw_effect,"Figure_14_environment_adjusted_candidate_effects",height=120);export_plot(draw_reaction,"Figure_15_candidate_reaction_norms",height=115);export_plot(draw_boundary,"Figure_16_empirical_failure_frequency",height=120)
nrob<-sum(summ$effect_class=="robust_advantage",na.rm=TRUE);nstable<-sum(summ$sensitivity_class=="pressure_stable",na.rm=TRUE);report<-paste0("# 环境校正材料效应与失效边界\n\n## 设计\n\n以育种圃×实际环境为聚类单位，并从环境压力估计中排除14个焦点材料。候选效应为候选在同环境非候选背景分布中的中秩百分位减0.5；负值表示优于环境中位水平。原始病害差保留为辅助字段。反应规范斜率描述环境压力升高时相对排名优势是否衰减。95%区间来自",B,"次环境簇bootstrap。结构性缺失不填补，不构造完整材料×年度面板。\n\n## 结果\n\n14个材料中",nrob,"个的环境校正效应95%区间完全低于0；",nstable,"个材料的压力敏感性区间跨越0，可归为在现有压力范围内未检测到系统性优势衰减。材料层面的失效频率和经验压力边界见表07。\n\n## 解释限制\n\n环境压力与育种圃材料构成共同变化，反应规范是描述性关联而非因果耐压参数。候选进入环境并非随机，bootstrap只传播已观测环境间变异，不能覆盖未观测目标环境。零膨胀和环境基线压缩会降低弱环境中的分辨率。\n")
writeLines(report,file.path(repdir,"environment_adjusted_response_report.md"),useBytes=TRUE)
qa<-paste0("# QA\n\n- 输入主长表30475行，排除15HZAN。\n- 环境压力仅由非14候选材料估计，减少循环定义。\n- 分析单位为候选×育种圃环境；同环境重复先取中位数。\n- 无缺失单元填补，无完整重复面板假设。\n- 不确定性采用",B,"次环境簇bootstrap，并补充逐年剔除。\n- 图件全由R生成，183 mm宽，SVG/PDF/600 dpi TIFF/PNG。\n")
writeLines(qa,file.path(repdir,"QA_notes.md"),useBytes=TRUE);sink(file.path(logdir,"sessionInfo.txt"));print(sessionInfo());sink()
meta<-data.frame(metric=c("input_rows","linked_gid_rows","environments","candidate_environment_events","portfolio_gid","bootstrap_iterations","robust_adjusted_advantage","pressure_stable"),value=c(input_rows,nrow(d),nrow(env),nrow(ce),length(ids),B,nrob,nstable));write_out(meta,"00_analysis_summary.csv");cat(paste(meta$metric,meta$value,sep="="),sep="\n")
